SELECT A.ANIMAL_ID, A.NAME
-- 아이디와 이름을 조회
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
-- LEFT JOIN 
ON A.ANIMAL_ID = B.ANIMAL_ID
-- ANIMAL_OUTS 테이블의 ANIMAL_ID는 ANIMAL_INS의 ANIMAL_ID의 외래 키
WHERE A.DATETIME > B.DATETIME
-- 보호 시작일(A.DATETIME)보다 입양일(B.DATETIME)이 더 빠른 동물
ORDER BY A.DATETIME
-- 보호 시작일이 빠른 순으로 조회